Add colour highlighting to exe failures

diff --git a/nengo_bones/templates/base_script.sh.template b/nengo_bones/templates/base_script.sh.template
--- a/nengo_bones/templates/base_script.sh.template
+++ b/nengo_bones/templates/base_script.sh.template
@@ -15,7 +15,7 @@ exe() {
     for i in "${!args[@]}"; do
       [ -n "${args[$i]}" ] || unset "args[$i]"
     done
-    "${args[@]}" || STATUS=1;
+    "${args[@]}" || { echo -e "\033[1;31mCOMMAND '${args[0]}' FAILED\033[0m"; STATUS=1; }
 }
 
 if [[ ! -e {{ pkg_name }} ]]; then
